### ISSUE TITLE
consider disabling JIT in JavaScript engines

### ISSUE THREAD

**Issue by smcv** [libproxy/libproxy#143]
While discussing mozjs, Mozilla developer @jcristau pointed out that when Firefox processes PAC, it disables JIT to reduce the attack surface (https://bugzilla.mozilla.org/show_bug.cgi?id=1607494).

If libproxy is built with the mozjs backend (despite the reasoning given on #139, which seems valid), it should maybe do the same. This patch from Julien Cristau compiles but is otherwise untested, so I'm not sending it as a merge request.

```diff
diff --git a/libproxy/modules/pacrunner_mozjs.cpp b/libproxy/modules/pacrunner_mozjs.cpp
index a8fb59a..0170671 100644
--- a/libproxy/modules/pacrunner_mozjs.cpp
+++ b/libproxy/modules/pacrunner_mozjs.cpp
@@ -38,6 +38,7 @@ using namespace libproxy;
 #include <js/Initialization.h>
 #include <js/CallArgs.h>
 #include <js/CompilationAndEvaluation.h>
+#include <js/ContextOptions.h>
 #include <js/MemoryFunctions.h>
 #include <js/SourceText.h>
 
@@ -122,6 +123,8 @@ public:
                // Initialize Javascript context
                if (!(this->jsctx = JS_NewContext(1024 * 1024)))     goto error;
                {
+                        JS::ContextOptionsRef(this->jsctx).setIon(false);
+
                        if (!JS::InitSelfHostedCode(this->jsctx)) goto error;
 
                        JS::RootedValue  rval(this->jsctx);
```

If WebKitGTK has an equivalent, it would probably be good to do that too.

**Comment by mcatanzaro** [comment]
> If WebKitGTK has an equivalent, it would probably be good to do that too.

Using the modern JSC API, you can call jsc_options_set_boolean() with JSC_OPTIONS_USE_JIT. (I don't know how to do it with the legacy JS API that libproxy currently uses.)

There's some value to doing this, because libproxy executes JS in-process, and unsandboxed. If the PAC file is malicious, it can tell your web browser to send all your HTTP/HTTPS requests via a naughty that injects naughty JS into your web browser, but web browsers execute JS in sandboxed subprocesses, which is safer.

**Comment by janbrummer** [comment]
Closing as obsolete.
