### ISSUE TITLE
Libproxy always returning direct:// even though I'm behind a proxy server?

### ISSUE THREAD

**Issue by ghost** [libproxy/libproxy#184]
Hi, this is more of a usage question than an issue. I'm running some basic tests with two Ubuntu 22.04 VMs, one of which has a proxy server running (no authentication, etc), and the other which connects to the Internet through the server. I've set the http_proxy and https_proxy environment variables to point to the proxy server's address, and everything seems to be working as expected.

I'm now testing libproxy through its Rust bindings, by running a small program which simply takes an URL and returns the list of proxies that should be used to access it. However, I notice that the program always outputs `direct://` instead of `http://my-proxy-server:port` as I would expect. Is this behavior correct? If so, would I still see `direct://` if I was behind a WPAD setup? I assume not, but at this point I'm not sure.

Thanks.

**Comment by DimStar77** [comment]
I'd start with verifying the configuration and see what the libproxy provided test program 'proxy`' returns.

simply call:

`proxy https://www.google.com` => does that return direct? Then your config might not be correct.

To get some more debug information, you can run:

`_PX_DEBUG=1 _MM_DEBUG=1 proxy https://www.google.com`

**Comment by martingalvan-nordic** [comment]
Hi @DimStar77 thanks for the response. What configuration are you referring to? I'm pretty sure I've set up the environment correctly, since I don't have an Internet connection unless I specify the address:port of my proxy server VM through the environment variables.

Running the command shows the following:

```
http_proxy=http://10.10.10.2:3128 https_proxy=http://10.10.10.2:3128 _PX_DEBUG=1 _MM_DEBUG=1 proxy https://www.google.com
success : builtin module envvar_config_extension
	Registering 23envvar_config_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::config_extension; bool sngl = false])
success : builtin module domain_ignore_extension
	Registering 23domain_ignore_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::ignore_extension; bool sngl = false])
success : builtin module hostname_ignore_extension
	Registering 25hostname_ignore_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::ignore_extension; bool sngl = false])
success : builtin module ip_ignore_extension
	Registering 19ip_ignore_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::ignore_extension; bool sngl = false])
success : builtin module dns_alias_wpad_extension
	Registering 24dns_alias_wpad_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::wpad_extension; bool sngl = false])
success : /usr/lib/x86_64-linux-gnu/libproxy/0.4.17/modules/config_gnome3.so
	Registering 22gnome_config_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::config_extension; bool sngl = false])
success : /usr/lib/x86_64-linux-gnu/libproxy/0.4.17/modules/network_networkmanager.so
	Registering 32networkmanager_network_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::network_extension; bool sngl = false])
preload : /usr/lib/x86_64-linux-gnu/libproxy/0.4.17/modules/config_gnome3.so
preload : /usr/lib/x86_64-linux-gnu/libproxy/0.4.17/modules/network_networkmanager.so
Configuration extension is: 22gnome_config_extension
Ignored list is: localhost,127.0.0.0/8,::1
Config is: 
direct://
```

I saw there's some code in the libproxy sources meant to inspect the `http_proxy` and `https_proxy` environment variables, so I was expecting that would be used.

**Comment by DimStar77** [comment]
```
success : /usr/lib/x86_64-linux-gnu/libproxy/0.4.17/modules/config_gnome3.so
	Registering 22gnome_config_extension(static const char* libmodman::extension<basetype, sngl>::base_type() [with basetype = libproxy::config_extension; bool sngl = false])
```

you are in a GNOME 3 session - the only relevant configuration is the Network Configuration in gnome-control-center.

**Comment by martingalvan-nordic** [comment]
Interesting. Setting the proxy server info there does give me the expected results. Is there any documentation as to which configs apply on which cases? I would've expected that the environment variables by themselves would work; AFAIK gnome-control-center simply sets the environment variables with the info the user places there. I'm likely wrong, though (there's probably more stuff done under the hood).

**Comment by DimStar77** [comment]
g-c-c does not set envvars; let alone that envvar could not have a valid setting for wpad or wpad-autodetection based on DNS.

and envvar is generally only valid for cli tools, but not for GUI tools

Libproxy tries to make 'the session configuration valid for everything'

i.e.:
* inside a GNOME session you configure the proxy in gnome config
* inside a KDE session, you configure the proxy in the KDE configs
* on Windows we read the registry to get the 'internet settings'
* on Macos it reads the global system settings
* in other cases, we have to try to fallback to envvar, as there is no better suitable config module available

for envvar, we extended the format a bit 'to our needs', so we accept http_proxy="wpad://' to to proxy auto-detection or http_proxy="pac+http://url.to.wpad.dat" for pad file without using wpad (that format might not be understood by all apps interpreting http_proxy directly instead of asking libproxy)

the advantage to the user for us reading the GNOME setting is, for example, that even an already running terminal gets the correct proxy when the settings are changed. envvar would only be re-exported on relaunch of a terminal

**Comment by DimStar77** [comment]
> > g-c-c does not set envvars
> 
> I may be wrong, but through quick testing I see that the variables are unset if I disable the "Network Proxy" option in the GNOME GUI, and are set again if I enable it.
> 
> Still, what you say makes sense. Is there a place where this is officially documented?

Depends largely on the distro and the used terminals. It's not a reliable thing to happen (and, as said, wpad and pac are not supported)

**Comment by martingalvan-nordic** [comment]
Alright, thanks!

**Comment by DimStar77** [comment]
> So a comment related to this: it seems like libproxy will always return `direct://` if we don't specify the protocol for the URL, e.g. `proxy www.google.com`. If we do `proxy https://www.google.com` then we do get the appropriate proxy info. I'm guessing that this is expected behavior since we need to explicitly state the protocol for libproxy to know what to do, correct?

correct
