### ISSUE TITLE
Why not duktape on Windows?

### ISSUE THREAD

**Issue by illera88** [libproxy/libproxy#193]
Hi,

Why don't you allow for ducktape to be used on Windows?

https://github.com/libproxy/libproxy/blob/master/libproxy/cmake/modules/pacrunner_duktape.cmk#L1-L3

**Comment by illera88** [comment]
can you format the code properly please?

**Comment by illera88** [comment]
why do you add this?
```
#ifndef INET_ADDRSTRLEN
#define INET_ADDRSTRLEN 16
#endif

#ifndef INET6_ADDRSTRLEN
#define INET6_ADDRSTRLEN 46
#endif
```

Your code has:
```
static char* dnsResolve_(const char* hostname)
{
#ifdef WIN32
// Initialize Winsock
WSADATA wsaData;
if (WSAStartup(MAKEWORD(2, 2), &wsaData))
return nullptr; // Why that return?
#endif
```

Why the return in windows?

You are forgetting to do:
```
#ifdef _WIN32
    WSACleanup();
#endif
```
At the end.

You can checkout my PR here https://github.com/libproxy/libproxy/pull/194

**Comment by thompsow** [comment]
I did this code before there was even a pacrunner_duktape.cpp (for Linux), before that pacrunner, I was using v8 which was a lot heavier (compilation) than needed by pacrunner module use case.

I did not see the bad formatting of my code sample, it looks horrible, do not know what went wrong in this editor. In any case, it looks like you were able to get something from my example.

I looked at your PR and added a comment about use of WIN32, instead of _WIN32, to avoid any clash with other Microsoft internal use of _WIN32 (reserved).

I am on another project, but do see that I did not do a WSACleanup(), so thanks. This code has been running without issue for well over a year and it never once gave an issue. Probably because the pacrunner does only small JS jobs of resolving URL by PAC script (typically small JS functions).

My code for pacrunner_duktape.cmk would not be of much help because it uses hardcoded paths to my build packages directory. You have the right idea, though.

**Comment by thompsow** [comment]
AS for the following and why I added it:

#ifndef INET_ADDRSTRLEN
#define INET_ADDRSTRLEN 16
#endif

#ifndef INET6_ADDRSTRLEN
#define INET6_ADDRSTRLEN 46
#endif

My code depends on those being defined and there are some order of header includes where they are not defined, yet. That code always insures that they are defined for my compiler.

**Comment by thompsow** [comment]
The other code:

static char* dnsResolve_(const char* hostname)
{
#ifdef WIN32
// Initialize Winsock
WSADATA wsaData;
if (WSAStartup(MAKEWORD(2, 2), &wsaData))
return nullptr; // Why that return?
#endif

I seem to remember that it was added because there was some issue in the duktape code, but I can not remember what it was. It may be that you are asking about why return nullptr, instead of NULL? In that case, it was I also do a lot of C++ coding in other projects and switching back and forth. You will see I also do not use C casting style, so you will see use of static_cast<>, as well.

**Comment by janbrummer** [comment]
Closing as obsolete.
