### ISSUE TITLE
allow export to cmake

### ISSUE THREAD

**Issue by goya** [libproxy/libproxy#221]
- allow export to cmake for people using the most used build system in the world

**Comment by janbrummer** [comment]
What exactly do you propose?

**Comment by janbrummer** [comment]
Right, another build system is not an option. Closing.

**Comment by eli-schwartz** [comment]
I think the idea here is actually to create cmake's Not Invented Here equivalent to pkg-config files, for when you want to build libproxy with meson and then link to libproxy from your own software that builds with cmake.

It's still wrong though -- cmake encourages the following options in descending order of preference:
- bug your dependencies and ask them to switch to cmake, and use cmake's target export functionality
- write your own FindFoobar.cmake script that manually searches to see if `-lproxy` and `#include <proxy.h>` exists "somewhere"
- use cmake's `pkg_check_modules()` function that searches for libproxy-1.0.pc


Apparently, writing your own FindFoobar.cmake script in each and every single project, is *better* in the eyes of the cmake developers than assuming that pkg-config is installed. :shrug: Personally, I recommend just using the third option. You can get pkg-config dependencies in your own cmake projects just fine.

P.S. Asking to create cmake's Not Invented Here equivalent to pkg-config files is tantamount to asking to port away from meson and over to cmake, because cmake-config files are... ruinously complex and you're expected to use cmake itself to generate them. That being said, you could write a static Findlibproxy-1.0.cmake script that just manually searches to see if `-lproxy` and `#include <proxy.h>` exists, and install that script from meson. It will "probably" work in the simple cases at least.
