### ISSUE TITLE
Library naming and soname inconsistency

### ISSUE THREAD

**Issue by seb128** [libproxy/libproxy#279]
Building 0.5.3 on Ubuntu (but git seems to have the same issue) gives a symlink

libproxy.so.1 -> libproxy.so.0.5.3

the naming is inconsistent, .so.1 means the soname version is 1 but then the actually library is named .0.5.3. The first digit there usually matches the soname

**Comment by smcv** [comment]
A more serious impact of this is that if there is a stale copy of libproxy 0.4.x (`libproxy.so.1.0.0`) in one of the system library directories (perhaps left over from a manual installation), `ldconfig` will think that `libproxy.1.0.0` is newer than `libproxy.0.5.3`, and set up the `libproxy.so.1` symlink to point to `libproxy.1.0.0`.

If you would like the ABI version number in the library name to be aligned with the human-readable version number, then I would suggest special-casing the build system so that libproxy x.y.z produces `libproxy.so.(x+1).y.z`. And then, if there is an ABI break at some point in the future (presumably unlikely because that goes against the goals of this library), both version numbers could increase to 2 to get back into sync.

**Comment by janbrummer** [comment]
We also had a internal discussion regarding this point and as you wrote: it's not against the flow and we will stick to the current implementation until we raise the version in future releases. Thanks for the hint, we will keep it in mind.

**Comment by smcv** [comment]
Is there a plan for how to address https://github.com/libproxy/libproxy/issues/279#issuecomment-1966302215 until then?
